<?php

namespace Database\Seeders;

use App\Models\Event;
use Illuminate\Database\Seeder;

class EventSeeder extends Seeder
{
    /**
     * Seed sample events into the database.
     */
    public function run(): void
    {
        $events = [
            [
                'title' => 'Indonesia Tech Summit 2024: AI & The Future',
                'organizer' => 'TechLink Hub',
                'organizer_type' => 'Company',
                'category' => 'Conference',
                'mode' => 'Online',
                'price' => 'Free',
                'date' => 'Oct 15, 2024 • 09:00 AM WIB',
                'short_date' => 'Oct 15, 2024',
                'full_date' => 'Tuesday, October 15, 2024',
                'time' => '09:00 - 15:00 (WIB)',
                'location' => 'Online Webinar',
                'quota' => '500 Peserta',
                'total_quota' => 500,
                'contact_email' => 'contact@technusa.co.id',
                'contact_phone' => '+62 812-3456-7890',
                'description' => 'Konferensi teknologi berskala nasional yang mempertemukan para pemimpin industri teknologi, peneliti AI, pendiri startup, dan praktisi IT dari seluruh Indonesia.',
                'what_you_will_learn' => [
                    'The state of AI and Machine Learning adoption in SEA.',
                    'Building scalable AI-powered microservices.',
                    'Best practices for enterprise security and ethics in AI.',
                    'Networking with top tech leads and CTOs.',
                ],
                'speakers' => [
                    ['name' => 'Budi Santoso', 'role' => 'Senior AI Researcher at Gojek', 'avatar' => 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&h=120&fit=crop'],
                    ['name' => 'Siti Rahma', 'role' => 'Lead Data Scientist at Tokopedia', 'avatar' => 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&h=120&fit=crop'],
                ],
                'image' => 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=500&fit=crop',
                'status' => 'Approved',
                'is_verified' => true,
            ],
            [
                'title' => 'Fullstack Development Bootcamp Preview',
                'organizer' => 'CodeCamp ID',
                'organizer_type' => 'Community',
                'category' => 'Workshop',
                'mode' => 'In-Person',
                'price' => 'Rp 150.000',
                'date' => 'Oct 18, 2024 • 13:00 PM WIB',
                'short_date' => 'Oct 18, 2024',
                'full_date' => 'Friday, October 18, 2024',
                'time' => '13:00 - 17:00 (WIB)',
                'location' => 'CoHive SCBD, Jakarta',
                'quota' => '50 Peserta',
                'total_quota' => 50,
                'contact_email' => 'info@codecamp.id',
                'contact_phone' => '+62 812-9988-7766',
                'description' => 'A hands-on preview session of our fullstack engineering curriculum covering Laravel, React, and DevOps deployment basics.',
                'what_you_will_learn' => [
                    'Fullstack architecture setup from scratch.',
                    'RESTful API creation with Laravel.',
                    'Frontend integration with React & Vite.',
                    'Deployment workflows to cloud VPS.',
                ],
                'speakers' => [
                    ['name' => 'Aditya Pratama', 'role' => 'Principal Engineer at CodeCamp ID', 'avatar' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&h=120&fit=crop'],
                ],
                'image' => 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&h=500&fit=crop',
                'status' => 'Approved',
                'is_verified' => true,
            ],
            [
                'title' => 'Nusantara FinTech Hack 2024',
                'organizer' => 'Bank Indo & TechLink',
                'organizer_type' => 'Company',
                'category' => 'Hackathon',
                'mode' => 'Hybrid',
                'price' => 'Free',
                'date' => 'Oct 20-22, 2024',
                'short_date' => 'Oct 20-22, 2024',
                'full_date' => 'October 20-22, 2024',
                'time' => '09:00 - 21:00 (WIB)',
                'location' => 'Bandung & Remote',
                'quota' => '200 Tim',
                'total_quota' => 200,
                'contact_email' => 'hack@bankindo.co.id',
                'contact_phone' => '+62 857-1122-3344',
                'description' => '48-hour nationwide fintech hackathon solving financial inclusion, open banking APIs, and digital payment challenges in Indonesia.',
                'what_you_will_learn' => [
                    'Integrating Open Banking APIs.',
                    'Rapid prototyping under 48 hours.',
                    'Pitching solutions to fintech VC investors.',
                ],
                'speakers' => [
                    ['name' => 'Rizky Kurnia', 'role' => 'Head of Innovation at Bank Indo', 'avatar' => 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&h=120&fit=crop'],
                ],
                'image' => 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&h=500&fit=crop',
                'status' => 'Approved',
                'is_verified' => true,
            ],
            [
                'title' => 'Mastering UI/UX for Enterprise SaaS',
                'organizer' => 'Design Association',
                'organizer_type' => 'Community',
                'category' => 'Webinar',
                'mode' => 'Online',
                'price' => 'Free',
                'date' => 'Oct 25, 2024 • 19:00 PM WIB',
                'short_date' => 'Oct 25, 2024',
                'full_date' => 'Friday, October 25, 2024',
                'time' => '19:00 - 21:00 (WIB)',
                'location' => 'Zoom Online',
                'quota' => '250 Peserta',
                'total_quota' => 250,
                'contact_email' => 'contact@designassoc.org',
                'contact_phone' => '+62 813-4455-6677',
                'description' => 'Learn design systems, complex data table layouts, and dashboard UX patterns tailored for high-density enterprise SaaS applications.',
                'what_you_will_learn' => [
                    'Designing scalable Figma design systems.',
                    'Data visualization and complex dashboard UX.',
                    'User research methods for B2B SaaS.',
                ],
                'speakers' => [
                    ['name' => 'Dewi Anggraini', 'role' => 'Lead Product Designer at Traveloka', 'avatar' => 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&h=120&fit=crop'],
                ],
                'image' => 'https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e?w=800&h=500&fit=crop',
                'status' => 'Approved',
                'is_verified' => true,
            ],
            [
                'title' => 'TechLink Global Talent Expo',
                'organizer' => 'Ministry of Tech',
                'organizer_type' => 'University',
                'category' => 'Job Fair',
                'mode' => 'In-Person',
                'price' => 'Free',
                'date' => 'Nov 01-02, 2024',
                'short_date' => 'Nov 01-02, 2024',
                'full_date' => 'November 01-02, 2024',
                'time' => '09:00 - 17:00 (WIB)',
                'location' => 'JCC Senayan, Jakarta',
                'quota' => '500 Peserta',
                'total_quota' => 500,
                'contact_email' => 'expo@ministryoftech.go.id',
                'contact_phone' => '+62 811-2233-4455',
                'description' => "Indonesia's largest tech job fair featuring 100+ hiring tech companies, startup pitch stages, and on-site interview sessions.",
                'what_you_will_learn' => [
                    'Direct hiring interviews with tech recruiters.',
                    'Resume review sessions with engineering managers.',
                    'Career guidance keynotes.',
                ],
                'speakers' => [
                    ['name' => 'Hendra Wijaya', 'role' => 'Director of Talent Acquisition at Ministry of Tech', 'avatar' => 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&h=120&fit=crop'],
                ],
                'image' => 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&h=500&fit=crop',
                'status' => 'Approved',
                'is_verified' => true,
            ],
            [
                'title' => 'Modern Web Development Workshop: React & Next.js',
                'organizer' => 'TechLink Academy',
                'organizer_type' => 'Company',
                'category' => 'Workshop',
                'mode' => 'In-Person',
                'price' => 'Free',
                'date' => 'Oct 28, 2024 • 09:00 - 16:00 WIB',
                'short_date' => 'Oct 28, 2024',
                'full_date' => 'Saturday, October 28, 2024',
                'time' => '09:00 - 16:00 (WIB)',
                'location' => 'TechLink HQ, South Jakarta',
                'quota' => '100 Peserta',
                'total_quota' => 100,
                'contact_email' => 'academy@techlink.id',
                'contact_phone' => '+62 812-1111-2222',
                'description' => "Join this intensive, hands-on workshop designed to elevate your front-end development skills. This session focuses on modern web architecture using React and Next.js.\n\nWhether you're a vocational student looking to enter the tech industry or a junior developer looking to refine your skills, this workshop provides practical insights.",
                'what_you_will_learn' => [
                    'Component-based architecture and state management in React.',
                    'Server-side rendering and static site generation with Next.js.',
                    'Integrating Tailwind CSS for rapid responsive UI development.',
                    'Best practices for performance optimization and accessibility.',
                ],
                'speakers' => [
                    ['name' => 'Budi Santoso', 'role' => 'Senior Frontend Engineer at Gojek', 'avatar' => 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&h=120&fit=crop'],
                    ['name' => 'Siti Rahma', 'role' => 'Lead Developer at Tokopedia', 'avatar' => 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&h=120&fit=crop'],
                ],
                'image' => 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=1200&h=600&fit=crop',
                'status' => 'Approved',
                'is_verified' => true,
            ],
            [
                'title' => 'Vocational Career Fair 2024',
                'organizer' => 'SMK Negeri 1 Jakarta',
                'organizer_type' => 'School',
                'category' => 'Job Fair',
                'mode' => 'In-Person',
                'price' => 'Free',
                'date' => 'Nov 02, 2024',
                'short_date' => 'Nov 02, 2024',
                'full_date' => 'Saturday, November 02, 2024',
                'time' => '08:30 - 16:00 (WIB)',
                'location' => 'Aula Utama SMKN 1 Jakarta Pusat',
                'quota' => '300 Peserta',
                'total_quota' => 300,
                'contact_email' => 'humas@smkn1jakarta.sch.id',
                'contact_phone' => '+62 811-9876-5432',
                'description' => 'Pameran bursa kerja dan peluang magang industri khusus bagi siswa dan alumni SMK.',
                'what_you_will_learn' => [
                    'Peluang karir langsung di bidang IT.',
                    'Review CV dan portofolio langsung bersama HR.',
                ],
                'speakers' => [
                    ['name' => 'Ahmad Fauzi', 'role' => 'Kepala Hubin SMKN 1 Jakarta', 'avatar' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&h=120&fit=crop'],
                ],
                'image' => 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&h=500&fit=crop',
                'status' => 'Pending',
                'is_verified' => false,
            ],
            [
                'title' => 'University Coding Competition',
                'organizer' => 'ITB Student Council',
                'organizer_type' => 'University',
                'category' => 'Hackathon',
                'mode' => 'Hybrid',
                'price' => 'Rp 50.000',
                'date' => 'Dec 10 - Dec 12, 2024',
                'short_date' => 'Dec 10, 2024',
                'full_date' => 'Tuesday - Thursday, Dec 10-12, 2024',
                'time' => '09:00 - 18:00 (WIB)',
                'location' => 'Aula Barat Institut Teknologi Bandung',
                'quota' => '150 Tim',
                'total_quota' => 150,
                'contact_email' => 'competition@kabinetitb.or.id',
                'contact_phone' => '+62 857-1122-3344',
                'description' => 'Kompetisi pemrograman tingkat mahasiswa se-Indonesia untuk menyelesaikan studi kasus nyata industri software engineering.',
                'what_you_will_learn' => [
                    'Algoritma kompetitif dan struktur data tingkat lanjut.',
                    'Problem solving kolaboratif dalam tim.',
                ],
                'speakers' => [
                    ['name' => 'Prof. Hendra Gunawan', 'role' => 'Dosen Pembina Informatika ITB', 'avatar' => 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&h=120&fit=crop'],
                ],
                'image' => 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&h=500&fit=crop',
                'status' => 'Pending',
                'is_verified' => false,
            ],
        ];

        foreach ($events as $event) {
            Event::updateOrCreate(
                ['title' => $event['title']],
                $event
            );
        }
    }
}
