<?php

namespace Database\Seeders;

use App\Models\JobListing;
use Illuminate\Database\Seeder;

class JobListingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $jobs = [
            [
                'code' => 'JOB-8921',
                'title' => 'Senior Backend Developer (Laravel)',
                'company' => 'Bukalapak',
                'company_industry' => 'E-Commerce / Tech',
                'department' => 'Engineering',
                'type' => 'Full-time',
                'category' => 'jobs',
                'experience' => 'Senior',
                'salary_range' => '25jt+',
                'location' => 'Jakarta (Hybrid)',
                'location_full' => 'Jakarta Selatan, DKI Jakarta',
                'company_size' => '500+ Employees',
                'skills' => ['Laravel', 'PHP', 'MySQL', 'Redis', 'Docker', 'AWS'],
                'tags' => ['Engineering', 'Laravel', 'Full-time'],
                'description' => 'Senior Backend Developer untuk core platform. Desain API scalable, optimasi query, mentor junior. Stack: Laravel, PostgreSQL, Redis, Kafka, Kubernetes di AWS. Sistem high-traffic jutaan user per hari.',
                'requirements' => "- Minimum 5+ tahun pengalaman dalam pengembangan backend web skala besar.\n- Mahir arsitektur Laravel, RESTful API, dan microservices.\n- Pengalaman dengan Redis, Docker, CI/CD, dan cloud AWS.\n- Kemampuan problem-solving dan komunikasi tim yang baik.",
                'deadline' => '15 Jan 2025',
                'status' => 'Active',
                'tab_status' => 'active',
                'is_active' => true,
                'total_views' => 142,
                'applicants_count' => 18,
                'logo_color' => '#e60012',
                'logo_text' => 'BL',
                'logo_url' => 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=200&h=200&fit=crop',
                'image' => 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=400&h=200&fit=crop',
            ],
            [
                'code' => 'JOB-8920',
                'title' => 'Frontend Developer (React + TypeScript)',
                'company' => 'Traveloka',
                'company_industry' => 'Online Travel & Lifestyle',
                'department' => 'Engineering',
                'type' => 'Full-time',
                'category' => 'jobs',
                'experience' => 'Mid',
                'salary_range' => '15–25jt',
                'location' => 'Jakarta (On-site)',
                'location_full' => 'Tangerang / Jakarta Barat',
                'company_size' => '500+ Employees',
                'skills' => ['React', 'TypeScript', 'Tailwind', 'GraphQL', 'Git'],
                'tags' => ['Frontend', 'React', 'Full-time'],
                'description' => 'Bangun pengalaman booking travel next-gen. React, TypeScript, GraphQL. Fokus performa, aksesibilitas, DX. Kolaborasi designer, PM, dan backend di squad lintas fungsi.',
                'requirements' => "- 3+ tahun pengalaman frontend development menggunakan React & TypeScript.\n- Pemahaman mendalam state management, client performance, dan modern CSS.\n- Familiar dengan GraphQL dan integrasi REST API.",
                'deadline' => '20 Jan 2025',
                'status' => 'Active',
                'tab_status' => 'active',
                'is_active' => true,
                'total_views' => 98,
                'applicants_count' => 24,
                'logo_color' => '#ff6b35',
                'logo_text' => 'TK',
                'logo_url' => 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=200&h=200&fit=crop',
                'image' => 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=400&h=200&fit=crop',
            ],
            [
                'code' => 'JOB-8918',
                'title' => 'Full Stack Developer Intern',
                'company' => 'Gojek',
                'company_industry' => 'On-Demand & Payments',
                'department' => 'Engineering',
                'type' => 'Internship',
                'category' => 'internship',
                'experience' => 'Entry',
                'salary_range' => '< 8jt',
                'location' => 'Jakarta (Hybrid)',
                'location_full' => 'Jakarta Selatan, DKI Jakarta',
                'company_size' => '500+ Employees',
                'skills' => ['Go', 'React', 'PostgreSQL', 'Kubernetes', 'Git'],
                'tags' => ['Internship', 'Fullstack', 'Go'],
                'description' => 'Magang 6 bulan berbayar. Rotasi backend (Go, Kubernetes) dan frontend (React). Mentorship engineer senior. Proyek nyata dari hari pertama. Peluang konversi full-time. Terbuka untuk mahasiswa tingkat akhir atau fresh graduate.',
                'requirements' => "- Mahasiswa tingkat akhir atau fresh graduate jurusan Ilmu Komputer / Teknik Informatika.\n- Pernah membangun project dengan Go, Node.js, atau React.\n- Bersedia magang full-time 6 bulan.",
                'deadline' => '1 Feb 2025',
                'status' => 'Active',
                'tab_status' => 'active',
                'is_active' => true,
                'total_views' => 210,
                'applicants_count' => 67,
                'logo_color' => '#00aa13',
                'logo_text' => 'GJ',
                'logo_url' => 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=200&h=200&fit=crop',
                'image' => 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=400&h=200&fit=crop',
            ],
            [
                'code' => 'JOB-8915',
                'title' => 'Data Science Internship',
                'company' => 'Tokopedia',
                'company_industry' => 'E-Commerce',
                'department' => 'Data',
                'type' => 'Internship',
                'category' => 'internship',
                'experience' => 'Entry',
                'salary_range' => '< 8jt',
                'location' => 'Jakarta (Remote)',
                'location_full' => 'Jakarta / Remote',
                'company_size' => '500+ Employees',
                'skills' => ['Python', 'PostgreSQL', 'Git'],
                'tags' => ['Data', 'Python', 'Internship'],
                'description' => 'Kerjakan recommendation system, demand forecasting, dan analisis perilaku user. Python, SQL, cloud ML. Kolaborasi data engineer dan product. Lingkungan belajar dengan tech talk dan hackathon mingguan.',
                'requirements' => "- Mahir Python data stack: Pandas, NumPy, Scikit-Learn, SQL.\n- Memahami konsep dasar machine learning dan statistika terapan.\n- Memiliki portofolio analisis data atau model ML.",
                'deadline' => '10 Feb 2025',
                'status' => 'Active',
                'tab_status' => 'active',
                'is_active' => true,
                'total_views' => 156,
                'applicants_count' => 45,
                'logo_color' => '#007bff',
                'logo_text' => 'TP',
                'logo_url' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=200&h=200&fit=crop',
                'image' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=200&fit=crop',
            ],
            [
                'code' => 'JOB-8912',
                'title' => 'Freelance Laravel Developer',
                'company' => 'Kredivo',
                'company_industry' => 'Fintech',
                'department' => 'Engineering',
                'type' => 'Contract',
                'category' => 'freelance',
                'experience' => 'Mid',
                'salary_range' => '15–25jt',
                'location' => 'Remote (Indonesia)',
                'location_full' => 'Remote (Indonesia)',
                'company_size' => '201-500 Employees',
                'skills' => ['Laravel', 'PHP', 'MySQL', 'REST API', 'Docker', 'Git'],
                'tags' => ['Freelance', 'Laravel', 'Contract'],
                'description' => 'Kontrak 3 bulan: merchant dashboard baru. Laravel, Blade, Tailwind. Clean architecture, TDD. Jam fleksibel, sync mingguan. Rate 15–25jt/bulan. Minimal 3 tahun Laravel + portfolio.',
                'requirements' => "- Minimal 3 tahun pengalaman profesional dengan Laravel.\n- Terbiasa integrasi REST API pihak ketiga dan payment gateway.\n- Portofolio website/aplikasi live wajib disertakan.",
                'deadline' => '31 Jan 2025',
                'status' => 'Active',
                'tab_status' => 'active',
                'is_active' => true,
                'total_views' => 84,
                'applicants_count' => 19,
                'logo_color' => '#7c3aed',
                'logo_text' => 'KD',
                'logo_url' => 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=200&h=200&fit=crop',
                'image' => 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=400&h=200&fit=crop',
            ],
            [
                'code' => 'JOB-8908',
                'title' => 'UI/UX Designer (Freelance)',
                'company' => 'Ruangguru',
                'company_industry' => 'EdTech',
                'department' => 'Design',
                'type' => 'Contract',
                'category' => 'freelance',
                'experience' => 'Mid',
                'salary_range' => '8–15jt',
                'location' => 'Remote (Indonesia)',
                'location_full' => 'Remote (Indonesia)',
                'company_size' => '500+ Employees',
                'skills' => ['Figma', 'UI/UX'],
                'tags' => ['Design', 'Figma', 'Freelance'],
                'description' => 'Desain fitur mobile app ed-tech. Wireframe, mockup high-fidelity, prototype interaktif. Usability testing. Kerja dengan PM dan engineer. Proyek 2 bulan, bisa diperpanjang. Portfolio wajib.',
                'requirements' => "- Pengalaman 2+ tahun mendesain produk digital mobile dan web.\n- Mahir Figma, auto-layout, interactive component, dan design token.\n- Link portofolio (Behance / Dribbble / Website pribadi).",
                'deadline' => '15 Feb 2025',
                'status' => 'Active',
                'tab_status' => 'active',
                'is_active' => true,
                'total_views' => 73,
                'applicants_count' => 12,
                'logo_color' => '#f97316',
                'logo_text' => 'RG',
                'logo_url' => 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=200&h=200&fit=crop',
                'image' => 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=200&fit=crop',
            ],
            [
                'code' => 'JOB-8902',
                'title' => 'Remote Full Stack Engineer',
                'company' => 'Xendit',
                'company_industry' => 'Payment Gateway / Fintech',
                'department' => 'Engineering',
                'type' => 'Full-time',
                'category' => 'remote',
                'experience' => 'Senior',
                'salary_range' => '25jt+',
                'location' => 'Fully Remote (Indonesia)',
                'location_full' => 'Remote, Indonesia',
                'company_size' => '500+ Employees',
                'skills' => ['Node.js', 'React', 'TypeScript', 'PostgreSQL', 'AWS', 'Kubernetes', 'GraphQL'],
                'tags' => ['Remote', 'Node.js', 'React'],
                'description' => 'Posisi fully remote. Bangun payment infrastructure API se-SEA. Node.js, TypeScript, React, PostgreSQL, Kubernetes di AWS. Fokus kualitas kode, observability, security. Gaji kompetitif + equity. Budget home office.',
                'requirements' => "- 4+ tahun pengalaman full-stack dengan Node.js dan React/TypeScript.\n- Terbiasa sistem distributed, microservices, dan messaging queue.\n- Komunikasi bahasa Inggris yang baik.",
                'deadline' => '25 Jan 2025',
                'status' => 'Active',
                'tab_status' => 'active',
                'is_active' => true,
                'total_views' => 189,
                'applicants_count' => 41,
                'logo_color' => '#06b6d4',
                'logo_text' => 'XD',
                'logo_url' => 'https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=200&h=200&fit=crop',
                'image' => 'https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=400&h=200&fit=crop',
            ],
            [
                'code' => 'JOB-8898',
                'title' => 'Remote DevOps Engineer',
                'company' => 'Midtrans',
                'company_industry' => 'Payment Gateway',
                'department' => 'Engineering',
                'type' => 'Full-time',
                'category' => 'remote',
                'experience' => 'Mid',
                'salary_range' => '15–25jt',
                'location' => 'Fully Remote (Indonesia)',
                'location_full' => 'Remote, Indonesia',
                'company_size' => '201-500 Employees',
                'skills' => ['Docker', 'Kubernetes', 'AWS', 'Git'],
                'tags' => ['DevOps', 'Cloud', 'Remote'],
                'description' => 'Kelola cloud infrastructure payment gateway jutaan transaksi. IaC Terraform, CI/CD, monitoring Prometheus/Grafana. On-call rotation. Linux dan networking kuat. Sertifikasi AWS/CKAD plus.',
                'requirements' => "- Pengalaman 3+ tahun mengelola AWS cloud infrastructure dengan Terraform.\n- Mahir Docker, Kubernetes cluster orchestration, dan Helm.\n- Pengalaman mengelola monitoring tool Prometheus, Grafana, ELK.",
                'deadline' => '5 Feb 2025',
                'status' => 'Active',
                'tab_status' => 'active',
                'is_active' => true,
                'total_views' => 134,
                'applicants_count' => 28,
                'logo_color' => '#10b981',
                'logo_text' => 'MT',
                'logo_url' => 'https://images.unsplash.com/photo-1667372393119-4d4a4b5e8b0e?w=200&h=200&fit=crop',
                'image' => 'https://images.unsplash.com/photo-1667372393119-4d4a4b5e8b0e?w=400&h=200&fit=crop',
            ],
            [
                'code' => 'JOB-8895',
                'title' => 'Graduate Software Engineer Program',
                'company' => 'Bank BCA',
                'company_industry' => 'Banking & Financial Services',
                'department' => 'Engineering',
                'type' => 'Full-time',
                'category' => 'graduate',
                'experience' => 'Entry',
                'salary_range' => '8–15jt',
                'location' => 'Jakarta (On-site)',
                'location_full' => 'Jakarta Pusat, DKI Jakarta',
                'company_size' => '500+ Employees',
                'skills' => ['Java', 'Spring Boot', 'React', 'PostgreSQL', 'Docker'],
                'tags' => ['Graduate', 'Java', 'Banking'],
                'description' => 'Program graduate 18 bulan. Rotasi digital banking, core banking, data platform. Mentorship tech lead. Training teknis, leadership, proyek inovasi. Paket kompetitif. Terbuka untuk lulusan 2024/2025 CS atau terkait.',
                'requirements' => "- Lulusan S1 Ilmu Komputer, Sistem Informasi, atau Teknik Elektro.\n- IPK minimal 3.25.\n- Memahami dasar OOP (Java/C++/Python) dan Database SQL.",
                'deadline' => '1 Mar 2025',
                'status' => 'Active',
                'tab_status' => 'active',
                'is_active' => true,
                'total_views' => 312,
                'applicants_count' => 95,
                'logo_color' => '#1e3a8a',
                'logo_text' => 'BCA',
                'logo_url' => 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=200&h=200&fit=crop',
                'image' => 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=400&h=200&fit=crop',
            ],
            [
                'code' => 'JOB-8890',
                'title' => 'Graduate Data Analyst',
                'company' => 'Shopee',
                'company_industry' => 'E-Commerce / Tech',
                'department' => 'Data',
                'type' => 'Full-time',
                'category' => 'graduate',
                'experience' => 'Entry',
                'salary_range' => '8–15jt',
                'location' => 'Jakarta (Hybrid)',
                'location_full' => 'Jakarta Selatan, DKI Jakarta',
                'company_size' => '500+ Employees',
                'skills' => ['Python', 'PostgreSQL', 'Git'],
                'tags' => ['Data', 'Graduate', 'Shopee'],
                'description' => 'Graduate Data Program. Analitik e-commerce: akuisisi, retensi, GMV. Python, SQL, BigQuery. Rotasi marketplace, logistik, fintech. Kurikulum terstruktur. Performa tinggi bisa fast-track Data Scientist.',
                'requirements' => "- Fresh graduate jurusan Kuantitatif (Statistika, Matematika, Data Science, Teknik).\n- Lancar SQL query (window functions, CTEs) dan Python data analysis.\n- Kemampuan presentasi insight data secara persuasif.",
                'deadline' => '15 Mar 2025',
                'status' => 'Active',
                'tab_status' => 'active',
                'is_active' => true,
                'total_views' => 245,
                'applicants_count' => 74,
                'logo_color' => '#ee4d2d',
                'logo_text' => 'SP',
                'logo_url' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=200&h=200&fit=crop',
                'image' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=200&fit=crop',
            ],
            [
                'code' => 'JOB-8885',
                'title' => 'Mobile Developer (Flutter) — Contract',
                'company' => 'DANA',
                'company_industry' => 'Digital Wallet / Fintech',
                'department' => 'Engineering',
                'type' => 'Contract',
                'category' => 'freelance',
                'experience' => 'Mid',
                'salary_range' => '15–25jt',
                'location' => 'Remote (Indonesia)',
                'location_full' => 'Remote, Indonesia',
                'company_size' => '500+ Employees',
                'skills' => ['Flutter', 'REST API', 'Git'],
                'tags' => ['Flutter', 'Mobile', 'Contract'],
                'description' => 'Draft posting kontrak 6 bulan fitur super-app DANA. Flutter, Clean Architecture, BLoC. Testing unit/widget/integrasi. Code review. Jadwal fleksibel, deliverable bulanan.',
                'requirements' => "- Pengalaman Flutter development 2+ tahun.\n- Mahir BLoC / Riverpod state management pattern.\n- Minimal memiliki 1 aplikasi terbit di Google Play Store atau Apple App Store.",
                'deadline' => '20 Feb 2025',
                'status' => 'Draft',
                'tab_status' => 'drafts',
                'is_active' => false,
                'total_views' => 0,
                'applicants_count' => 0,
                'logo_color' => '#00bfa5',
                'logo_text' => 'DN',
                'logo_url' => 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=200&h=200&fit=crop',
                'image' => 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400&h=200&fit=crop',
            ],
            [
                'code' => 'JOB-8880',
                'title' => 'QA Engineer Intern (Closed)',
                'company' => 'JD.ID',
                'company_industry' => 'E-Commerce',
                'department' => 'Engineering',
                'type' => 'Internship',
                'category' => 'internship',
                'experience' => 'Entry',
                'salary_range' => '< 8jt',
                'location' => 'Jakarta (Hybrid)',
                'location_full' => 'Jakarta Barat, DKI Jakarta',
                'company_size' => '201-500 Employees',
                'skills' => ['Git', 'REST API'],
                'tags' => ['QA', 'Testing', 'Closed'],
                'description' => 'Closed listing: Belajar test automation web dan mobile. Tulis test case, automasi regresi, API dan load testing. Kerja di tim Scrum. Magang 4–6 bulan.',
                'requirements' => "- Terbiasa pengujian fungsional web dan Postman API testing.\n- Ketelitian tinggi terhadap edge case dan bug reporting.",
                'deadline' => '28 Feb 2024',
                'status' => 'Closed',
                'tab_status' => 'closed',
                'is_active' => false,
                'total_views' => 190,
                'applicants_count' => 52,
                'logo_color' => '#ff0055',
                'logo_text' => 'JD',
                'logo_url' => 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=200&h=200&fit=crop',
                'image' => 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=400&h=200&fit=crop',
            ],
        ];

        foreach ($jobs as $job) {
            JobListing::updateOrCreate(
                ['code' => $job['code']],
                $job
            );
        }
    }
}
