<?php

namespace Database\Seeders;

use App\Models\University;
use Illuminate\Database\Seeder;

class UniversitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $universities = [
            [
                'npsn' => '20109988',
                'name' => 'Institut Teknologi Bandung',
                'type' => 'Negeri',
                'city' => 'Bandung',
                'province' => 'Jawa Barat',
                'location' => 'Bandung, Jawa Barat',
                'address' => 'Jl. Ganesha No.10, Lb. Siliwangi, Kec. Coblong, Kota Bandung, Jawa Barat 40132',
                'status' => 'Active',
                'logo_name' => 'ITB_Logo.png',
                'logo_url' => 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=120&h=120&q=80',
                'logo_text' => 'ITB',
                'logo_bg' => 'bg-blue-700',
                'email' => 'info@itb.ac.id',
                'website' => 'https://www.itb.ac.id',
                'phone' => '022-2504780',
                'description' => 'Institut Teknologi Bandung (ITB) adalah perguruan tinggi negeri tertua di Indonesia yang berfokus pada sains, teknologi, dan seni. Terkenal dengan program teknik, sains, dan desain yang unggul secara internasional.',
                'tags' => ['Teknik', 'Sains', 'Desain', 'Arsitektur'],
                'total_students' => 30000,
                'total_faculties' => 12,
                'accreditation' => 'A',
                'founded' => 1920,
            ],
            [
                'npsn' => '20211234',
                'name' => 'Universitas Indonesia',
                'type' => 'Negeri',
                'city' => 'Depok',
                'province' => 'Jawa Barat',
                'location' => 'Depok, Jawa Barat',
                'address' => 'Kampus UI Depok, Jl. Prof. Dr. Ir. Soekarno, Kec. Beji, Kota Depok, Jawa Barat 16424',
                'status' => 'Active',
                'logo_name' => 'UI_Logo.png',
                'logo_url' => 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?auto=format&fit=crop&w=120&h=120&q=80',
                'logo_text' => 'UI',
                'logo_bg' => 'bg-yellow-600',
                'email' => 'humas@ui.ac.id',
                'website' => 'https://www.ui.ac.id',
                'phone' => '021-7888001',
                'description' => 'Universitas Indonesia (UI) adalah salah satu perguruan tinggi negeri terbaik di Indonesia dengan kampus utama di Depok. Memiliki 14 fakultas dan program studi unggulan di bidang kedokteran, hukum, ekonomi, dan teknik.',
                'tags' => ['Kedokteran', 'Hukum', 'Ekonomi', 'Teknik', 'Ilmu Sosial'],
                'total_students' => 45000,
                'total_faculties' => 14,
                'accreditation' => 'A',
                'founded' => 1849,
            ],
            [
                'npsn' => '70012555',
                'name' => 'Universitas Gadjah Mada',
                'type' => 'Negeri',
                'city' => 'Yogyakarta',
                'province' => 'DI Yogyakarta',
                'location' => 'Yogyakarta, DI Yogyakarta',
                'address' => 'Jl. Sosio Humaniora No.1, Bulaksumur, Kec. Mlati, Kabupaten Sleman, DI Yogyakarta 55281',
                'status' => 'Active',
                'logo_name' => 'UGM_Logo.png',
                'logo_url' => 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=120&h=120&q=80',
                'logo_text' => 'UGM',
                'logo_bg' => 'bg-red-700',
                'email' => 'ugm@ugm.ac.id',
                'website' => 'https://www.ugm.ac.id',
                'phone' => '0274-552810',
                'description' => 'Universitas Gadjah Mada (UGM) adalah universitas negeri tertua di Indonesia yang berdiri pada 1949. Terkenal sebagai "Perguruan Tinggi Pancasila" dengan 18 fakultas dan program unggulan di berbagai disiplin ilmu.',
                'tags' => ['Ilmu Sosial', 'Teknik', 'Pertanian', 'Kedokteran', 'Hukum'],
                'total_students' => 50000,
                'total_faculties' => 18,
                'accreditation' => 'A',
                'founded' => 1949,
            ],
            [
                'npsn' => '20301122',
                'name' => 'Institut Teknologi Sepuluh Nopember',
                'type' => 'Negeri',
                'city' => 'Surabaya',
                'province' => 'Jawa Timur',
                'location' => 'Surabaya, Jawa Timur',
                'address' => 'Kampus ITS Sukolilo, Jl. Raya ITS, Kec. Sukolilo, Kota Surabaya, Jawa Timur 60111',
                'status' => 'Active',
                'logo_name' => 'ITS_Logo.png',
                'logo_url' => 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=120&h=120&q=80',
                'logo_text' => 'ITS',
                'logo_bg' => 'bg-orange-600',
                'email' => 'humas@its.ac.id',
                'website' => 'https://www.its.ac.id',
                'phone' => '031-5923411',
                'description' => 'Institut Teknologi Sepuluh Nopember (ITS) adalah perguruan tinggi negeri yang berfokus pada teknologi maritim, teknik, dan sains. Terkenal dengan penelitian robotika, kelautan, dan energi terbarukan.',
                'tags' => ['Teknik Maritim', 'Robotika', 'Teknik Elektro', 'Teknik Mesin'],
                'total_students' => 25000,
                'total_faculties' => 7,
                'accreditation' => 'A',
                'founded' => 1957,
            ],
            [
                'npsn' => '20501987',
                'name' => 'Universitas Airlangga',
                'type' => 'Negeri',
                'city' => 'Surabaya',
                'province' => 'Jawa Timur',
                'location' => 'Surabaya, Jawa Timur',
                'address' => 'Kampus C Mulyorejo, Jl. Mulyorejo, Kec. Mulyorejo, Kota Surabaya, Jawa Timur 60115',
                'status' => 'Active',
                'logo_name' => 'UNAIR_Logo.png',
                'logo_url' => 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=120&h=120&q=80',
                'logo_text' => 'UNAIR',
                'logo_bg' => 'bg-purple-700',
                'email' => 'humas@unair.ac.id',
                'website' => 'https://www.unair.ac.id',
                'phone' => '031-5914040',
                'description' => 'Universitas Airlangga (UNAIR) adalah universitas negeri tertua di Jawa Timur dengan keunggulan di bidang kesehatan, kedokteran gigi, farmasi, dan keperawatan. Memiliki rumah sakit pendidikan sendiri.',
                'tags' => ['Kedokteran', 'Kedokteran Gigi', 'Farmasi', 'Keperawatan', 'Kesehatan Masyarakat'],
                'total_students' => 35000,
                'total_faculties' => 15,
                'accreditation' => 'A',
                'founded' => 1954,
            ],
            [
                'npsn' => '20601543',
                'name' => 'Universitas Diponegoro',
                'type' => 'Negeri',
                'city' => 'Semarang',
                'province' => 'Jawa Tengah',
                'location' => 'Semarang, Jawa Tengah',
                'address' => 'Kampus Undip Tembalang, Jl. Prof. H. Soedarto, S.H., Tembalang, Kota Semarang, Jawa Tengah 50275',
                'status' => 'Active',
                'logo_name' => 'UNDIP_Logo.png',
                'logo_url' => '',
                'logo_text' => 'UNDIP',
                'logo_bg' => 'bg-teal-700',
                'email' => 'humas@undip.ac.id',
                'website' => 'https://www.undip.ac.id',
                'phone' => '024-7474698',
                'description' => 'Universitas Diponegoro (Undip) adalah universitas negeri di Semarang dengan 11 fakultas. Terkenal dengan program teknik sipil, perikanan, dan ilmu kelautan yang unggul.',
                'tags' => ['Teknik Sipil', 'Perikanan', 'Kelautan', 'Hukum', 'Ekonomi'],
                'total_students' => 40000,
                'total_faculties' => 11,
                'accreditation' => 'A',
                'founded' => 1957,
            ],
            [
                'npsn' => '20701321',
                'name' => 'Universitas Hasanuddin',
                'type' => 'Negeri',
                'city' => 'Makassar',
                'province' => 'Sulawesi Selatan',
                'location' => 'Makassar, Sulawesi Selatan',
                'address' => 'Kampus UNHAS Tamalanrea, Jl. Perintis Kemerdekaan Km.10, Tamalanrea, Kota Makassar, Sulawesi Selatan 90245',
                'status' => 'Active',
                'logo_name' => 'UNHAS_Logo.png',
                'logo_url' => '',
                'logo_text' => 'UNHAS',
                'logo_bg' => 'bg-sky-700',
                'email' => 'humas@unhas.ac.id',
                'website' => 'https://www.unhas.ac.id',
                'phone' => '0411-585388',
                'description' => 'Universitas Hasanuddin (UNHAS) adalah universitas negeri terbesar di Indonesia Timur. Memiliki 14 fakultas dengan keunggulan di bidang kelautan, pertanian, dan kedokteran.',
                'tags' => ['Kelautan', 'Pertanian', 'Kedokteran', 'Teknik', 'Peternakan'],
                'total_students' => 32000,
                'total_faculties' => 14,
                'accreditation' => 'A',
                'founded' => 1956,
            ],
        ];

        foreach ($universities as $univ) {
            University::updateOrCreate(
                ['npsn' => $univ['npsn']],
                $univ
            );
        }
    }
}
