<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class IndustryController extends Controller
{
    public function index(Request $request)
    {
        $companies = [
            [
                'id' => 1,
                'name' => 'Bali Tech Solutions',
                'category' => 'Software Development',
                'category_slug' => 'software-development',
                'location' => 'Denpasar',
                'badge_class' => 'software',
                'description' => 'Membangun solusi perangkat lunak enterprise untuk bisnis lokal dan internasional.',
                'logo_bg' => '#eff6ff',
                'logo_color' => '#2563eb',
                'icon_type' => 'code',
                'employees' => '50-100 Karyawan',
                'website' => 'https://balitechsolutions.co.id',
                'email' => 'contact@balitechsolutions.co.id',
                'founded' => '2018',
                'tech_stack' => ['Laravel', 'React', 'Node.js', 'AWS', 'Docker'],
                'full_description' => 'Bali Tech Solutions adalah penyedia layanan rekayasa perangkat lunak terkemuka di Denpasar. Kami mengkhususkan diri dalam pengembangan aplikasi web enterprise, arsitektur microservices, dan integrasi cloud modern untuk klien global.',
            ],
            [
                'id' => 2,
                'name' => 'Island Software House',
                'category' => 'Creative Agency',
                'category_slug' => 'creative-agency',
                'location' => 'Badung',
                'badge_class' => 'creative',
                'description' => 'Agensi digital full-service yang fokus pada desain UI/UX dan web development.',
                'logo_bg' => '#f0fdf4',
                'logo_color' => '#16a34a',
                'icon_type' => 'palette',
                'employees' => '20-50 Karyawan',
                'website' => 'https://islandsoftwarehouse.id',
                'email' => 'hello@islandsoftwarehouse.id',
                'founded' => '2020',
                'tech_stack' => ['Figma', 'Vue.js', 'TailwindCSS', 'WordPress', 'Webflow'],
                'full_description' => 'Island Software House merancang dan meracik pengalaman digital yang estetis dan fungsional. Tim desainer dan pengembang kami berkolaborasi menciptakan identitas merek, desain produk interaktif, dan web aplikasi berkinerja tinggi.',
            ],
            [
                'id' => 3,
                'name' => 'Dewata Fintech',
                'category' => 'Startup',
                'category_slug' => 'startup',
                'location' => 'Denpasar',
                'badge_class' => 'startup',
                'description' => 'Inovasi pembayaran digital untuk UMKM di seluruh Bali dan sekitarnya.',
                'logo_bg' => '#fff1f2',
                'logo_color' => '#e11d48',
                'icon_type' => 'credit-card',
                'employees' => '15-30 Karyawan',
                'website' => 'https://dewatafintech.com',
                'email' => 'info@dewatafintech.com',
                'founded' => '2021',
                'tech_stack' => ['Golang', 'Flutter', 'PostgreSQL', 'Kubernetes', 'QRIS API'],
                'full_description' => 'Dewata Fintech memberdayakan pengusaha lokal Bali dengan sistem kasir pintar, transaksi QRIS instan, dan integrasi pembukuan digital otomatis untuk memajukan perekonomian daerah.',
            ],
            [
                'id' => 4,
                'name' => 'Ubud Dev Studio',
                'category' => 'Software Development',
                'category_slug' => 'software-development',
                'location' => 'Ubud',
                'badge_class' => 'software',
                'description' => 'Spesialis pengembangan aplikasi mobile dan sistem terdistribusi.',
                'logo_bg' => '#eff6ff',
                'logo_color' => '#2563eb',
                'icon_type' => 'building',
                'employees' => '30-50 Karyawan',
                'website' => 'https://ubuddevstudio.io',
                'email' => 'support@ubuddevstudio.io',
                'founded' => '2019',
                'tech_stack' => ['React Native', 'Kotlin', 'Swift', 'GraphQL', 'Firebase'],
                'full_description' => 'Ubud Dev Studio menghadirkan aplikasi iOS dan Android performa tinggi dengan filosofi pengembangan bersih dan teruji (Clean Code & TDD). Berbasis di pusat kebudayaan Ubud.',
            ],
            [
                'id' => 5,
                'name' => 'Canggu Digital',
                'category' => 'Creative Agency',
                'category_slug' => 'creative-agency',
                'location' => 'Canggu',
                'badge_class' => 'creative',
                'description' => 'Menciptakan pengalaman digital yang imersif dan branding visual.',
                'logo_bg' => '#f0fdf4',
                'logo_color' => '#16a34a',
                'icon_type' => 'magic',
                'employees' => '10-25 Karyawan',
                'website' => 'https://canggudigital.com',
                'email' => 'hi@canggudigital.com',
                'founded' => '2022',
                'tech_stack' => ['Three.js', 'Next.js', 'GSAP', 'Blender', 'TailwindCSS'],
                'full_description' => 'Canggu Digital mengombinasikan desain 3D WebGL, animasi dinamis, dan riset UX mendalam untuk bisnis pariwisata, gaya hidup, dan teknologi internasional di kawasan Canggu.',
            ],
            [
                'id' => 6,
                'name' => 'Sanur Tech',
                'category' => 'Startup',
                'category_slug' => 'startup',
                'location' => 'Sanur',
                'badge_class' => 'startup',
                'description' => 'Platform logistik pintar yang menghubungkan pengusaha lokal.',
                'logo_bg' => '#fff1f2',
                'logo_color' => '#e11d48',
                'icon_type' => 'rocket',
                'employees' => '25-60 Karyawan',
                'website' => 'https://sanurtech.id',
                'email' => 'partner@sanurtech.id',
                'founded' => '2021',
                'tech_stack' => ['Python', 'Django', 'FastAPI', 'Flutter', 'Redis'],
                'full_description' => 'Sanur Tech mengembangkan platform manajemen rantai pasok berbasis kecerdasan buatan untuk merasionalkan rute pengiriman dan logistik barang antar pulau di Indonesia.',
            ],
            [
                'id' => 7,
                'name' => 'Nusa Media Labs',
                'category' => 'Software Development',
                'category_slug' => 'software-development',
                'location' => 'Denpasar',
                'badge_class' => 'software',
                'description' => 'Pengembangan solusi AI, Big Data, dan analitik bisnis modern.',
                'logo_bg' => '#eff6ff',
                'logo_color' => '#2563eb',
                'icon_type' => 'cpu',
                'employees' => '40-80 Karyawan',
                'website' => 'https://nusamedia.id',
                'email' => 'info@nusamedia.id',
                'founded' => '2017',
                'tech_stack' => ['Python', 'TensorFlow', 'PyTorch', 'Apache Spark', 'AWS'],
                'full_description' => 'Nusa Media Labs adalah perusahaan analitik data dan pembelajaran mesin yang membantu perusahaan mengambil keputusan strategis berpatokan pada data riil.',
            ],
            [
                'id' => 8,
                'name' => 'Kuta Cloud Systems',
                'category' => 'Software Development',
                'category_slug' => 'software-development',
                'location' => 'Kuta',
                'badge_class' => 'software',
                'description' => 'Layanan otomatisasi infrastruktur cloud dan keamanan siber.',
                'logo_bg' => '#eff6ff',
                'logo_color' => '#2563eb',
                'icon_type' => 'cloud',
                'employees' => '15-40 Karyawan',
                'website' => 'https://kutacloud.co.id',
                'email' => 'ops@kutacloud.co.id',
                'founded' => '2019',
                'tech_stack' => ['Terraform', 'Kubernetes', 'AWS', 'GCP', 'Ansible'],
                'full_description' => 'Kuta Cloud Systems berfokus pada migrasi arsitektur cloud, DevOps CI/CD pipeline, serta perlindungan infrastruktur server dari serangan siber.',
            ],
            [
                'id' => 9,
                'name' => 'Seminyak Creative Tech',
                'category' => 'Creative Agency',
                'category_slug' => 'creative-agency',
                'location' => 'Seminyak',
                'badge_class' => 'creative',
                'description' => 'Spesialis branding digital, motion graphics, dan sistem desain web.',
                'logo_bg' => '#f0fdf4',
                'logo_color' => '#16a34a',
                'icon_type' => 'layers',
                'employees' => '12-25 Karyawan',
                'website' => 'https://seminyakcreative.com',
                'email' => 'hello@seminyakcreative.com',
                'founded' => '2020',
                'tech_stack' => ['Figma', 'After Effects', 'React', 'CSS Modules'],
                'full_description' => 'Seminyak Creative Tech menggabungkan estetika seni lokal Bali dengan teknologi front-end presisi tinggi untuk menghadirkan situs web berkelas dunia.',
            ],
            [
                'id' => 10,
                'name' => 'Dewata AI Labs',
                'category' => 'Startup',
                'category_slug' => 'startup',
                'location' => 'Denpasar',
                'badge_class' => 'startup',
                'description' => 'Platform agen kecerdasan buatan untuk otomatisasi layanan pelanggan.',
                'logo_bg' => '#fff1f2',
                'logo_color' => '#e11d48',
                'icon_type' => 'sparkles',
                'employees' => '10-20 Karyawan',
                'website' => 'https://dewata.ai',
                'email' => 'sales@dewata.ai',
                'founded' => '2023',
                'tech_stack' => ['Python', 'OpenAI API', 'LangChain', 'FastAPI', 'React'],
                'full_description' => 'Dewata AI Labs membangun solusi conversational AI yang membantu sektor perhotelan dan pariwisata menangani pertanyaan tamu 24/7 secara otomatis.',
            ],
            [
                'id' => 11,
                'name' => 'Jimbaran Cyber',
                'category' => 'Software Development',
                'category_slug' => 'software-development',
                'location' => 'Jimbaran',
                'badge_class' => 'software',
                'description' => 'Pengembangan peranti lunak khusus dan konsultasi IT terpadu.',
                'logo_bg' => '#eff6ff',
                'logo_color' => '#2563eb',
                'icon_type' => 'shield',
                'employees' => '30-70 Karyawan',
                'website' => 'https://jimbarancyber.id',
                'email' => 'info@jimbarancyber.id',
                'founded' => '2016',
                'tech_stack' => ['Java', 'Spring Boot', 'Angular', 'Oracle', 'Docker'],
                'full_description' => 'Jimbaran Cyber menyediakan solusi perbankan, sistem informasi rumah sakit, dan aplikasi pemerintahan dengan standar keamanan tinggi.',
            ],
            [
                'id' => 12,
                'name' => 'Benoa Web Studio',
                'category' => 'Creative Agency',
                'category_slug' => 'creative-agency',
                'location' => 'Benoa',
                'badge_class' => 'creative',
                'description' => 'Pemasaran digital, pembuatan konten kreatif, dan portal e-commerce.',
                'logo_bg' => '#f0fdf4',
                'logo_color' => '#16a34a',
                'icon_type' => 'globe',
                'employees' => '15-30 Karyawan',
                'website' => 'https://benoaweb.co.id',
                'email' => 'hello@benoaweb.co.id',
                'founded' => '2019',
                'tech_stack' => ['Shopify', 'Laravel', 'SEO Tools', 'Meta Ads', 'Google Ads'],
                'full_description' => 'Benoa Web Studio membantu merek lokal memperluas jangkuan pasar ekspor melalui optimasi mesin pencari, toko online, dan pemasaran digital berbasis performa.',
            ],
            [
                'id' => 13,
                'name' => 'Tabanan Code House',
                'category' => 'Software Development',
                'category_slug' => 'software-development',
                'location' => 'Tabanan',
                'badge_class' => 'software',
                'description' => 'Inovasi agritech dan otomatisasi IoT untuk pertanian berkelanjutan.',
                'logo_bg' => '#eff6ff',
                'logo_color' => '#2563eb',
                'icon_type' => 'terminal',
                'employees' => '20-40 Karyawan',
                'website' => 'https://tabanancode.id',
                'email' => 'contact@tabanancode.id',
                'founded' => '2020',
                'tech_stack' => ['C++', 'Python', 'MQTT', 'Raspberry Pi', 'Vue.js'],
                'full_description' => 'Tabanan Code House berfokus pada integrasi peranti keras sensor IoT dan aplikasi pemantauan iklim mikro untuk mendukung sektor pertanian organik Bali.',
            ],
            [
                'id' => 14,
                'name' => 'Singaraja Tech',
                'category' => 'Startup',
                'category_slug' => 'startup',
                'location' => 'Singaraja',
                'badge_class' => 'startup',
                'description' => 'Platform edutech dan pelatihan talenta pemrograman Bali Utara.',
                'logo_bg' => '#fff1f2',
                'logo_color' => '#e11d48',
                'icon_type' => 'graduation-cap',
                'employees' => '10-25 Karyawan',
                'website' => 'https://singarajatech.org',
                'email' => 'info@singarajatech.org',
                'founded' => '2022',
                'tech_stack' => ['Laravel', 'AlpineJS', 'TailwindCSS', 'MySQL'],
                'full_description' => 'Singaraja Tech memberdayakan pemuda dan mahasiswa Bali Utara dengan kurikulum coding intensif, bootcamp, dan penyaluran kerja ke industri digital.',
            ],
            [
                'id' => 15,
                'name' => 'Uluwatu Digital Innovation',
                'category' => 'Creative Agency',
                'category_slug' => 'creative-agency',
                'location' => 'Uluwatu',
                'badge_class' => 'creative',
                'description' => 'Studio kreatif dan produksi konten digital bernilai tinggi.',
                'logo_bg' => '#f0fdf4',
                'logo_color' => '#16a34a',
                'icon_type' => 'camera',
                'employees' => '8-18 Karyawan',
                'website' => 'https://uluwatudigital.com',
                'email' => 'hi@uluwatudigital.com',
                'founded' => '2021',
                'tech_stack' => ['Premiere Pro', 'Figma', 'Webflow', 'Node.js'],
                'full_description' => 'Uluwatu Digital Innovation menghadirkan narasi visual yang kuat, sinematografi brand, dan situs web interaktif untuk resort mewah dan destinasi eksklusif.',
            ],
        ];

        return view('industry.industry', compact('companies'));
    }
}
