<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class IndustryController extends Controller
{
    public function index(Request $request)
    {
        $companies = [
            [
                'id' => 1,
                'name' => 'Bali Tech Solutions',
                'category' => 'Software Development',
                'category_slug' => 'software-development',
                'location' => 'Denpasar',
                'badge_class' => 'software',
                'description' => 'Membangun solusi perangkat lunak enterprise untuk bisnis lokal dan internasional.',
                'logo_bg' => '#eff6ff',
                'logo_color' => '#2563eb',
                'icon_type' => 'code',
                'employees' => '50-100 Karyawan',
                'website' => 'https://balitechsolutions.co.id',
                'email' => 'contact@balitechsolutions.co.id',
                'founded' => '2018',
                'rating' => '4.9',
                'projects_completed' => '120+ Proyek',
                'verified' => true,
                'logo_image' => 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=300&h=300&fit=crop',
                'cover_image' => 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1000&h=400&fit=crop',
                'specialties' => ['Enterprise Web Apps', 'Microservices Architecture', 'Cloud Integration & DevOps'],
                'tech_stack' => ['Laravel', 'React', 'Node.js', 'AWS', 'Docker'],
                'full_description' => 'Bali Tech Solutions adalah penyedia layanan rekayasa perangkat lunak terkemuka di Denpasar. Kami mengkhususkan diri dalam pengembangan aplikasi web enterprise, arsitektur microservices, dan integrasi cloud modern untuk klien global.',
            ],
            [
                'id' => 2,
                'name' => 'Island Software House',
                'category' => 'Creative Agency',
                'category_slug' => 'creative-agency',
                'location' => 'Badung',
                'badge_class' => 'creative',
                'description' => 'Agensi digital full-service yang fokus pada desain UI/UX dan web development.',
                'logo_bg' => '#f0fdf4',
                'logo_color' => '#16a34a',
                'icon_type' => 'palette',
                'employees' => '20-50 Karyawan',
                'website' => 'https://islandsoftwarehouse.id',
                'email' => 'hello@islandsoftwarehouse.id',
                'founded' => '2020',
                'rating' => '4.8',
                'projects_completed' => '85+ Proyek',
                'verified' => true,
                'logo_image' => 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=300&h=300&fit=crop',
                'cover_image' => 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=1000&h=400&fit=crop',
                'specialties' => ['Brand Identity & UI/UX', 'Headless CMS Web Development', 'Interactive Design'],
                'tech_stack' => ['Figma', 'Vue.js', 'TailwindCSS', 'WordPress', 'Webflow'],
                'full_description' => 'Island Software House merancang dan meracik pengalaman digital yang estetis dan fungsional. Tim desainer dan pengembang kami berkolaborasi menciptakan identitas merek, desain produk interaktif, dan web aplikasi berkinerja tinggi.',
            ],
            [
                'id' => 3,
                'name' => 'Dewata Fintech',
                'category' => 'Startup',
                'category_slug' => 'startup',
                'location' => 'Gianyar',
                'badge_class' => 'startup',
                'description' => 'Inovasi pembayaran digital untuk UMKM di seluruh Bali dan sekitarnya.',
                'logo_bg' => '#fff1f2',
                'logo_color' => '#e11d48',
                'icon_type' => 'credit-card',
                'employees' => '10-20 Karyawan',
                'website' => 'https://dewatafintech.co.id',
                'email' => 'support@dewatafintech.co.id',
                'founded' => '2021',
                'rating' => '5.0',
                'projects_completed' => '25k+ Merchant',
                'verified' => true,
                'logo_image' => 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=300&h=300&fit=crop',
                'cover_image' => 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=1000&h=400&fit=crop',
                'specialties' => ['POS Kasir Pintar QRIS', 'Pembukuan Digital Otomatis', 'API Integrasi Pembayaran'],
                'tech_stack' => ['Golang', 'Flutter', 'PostgreSQL', 'Kubernetes', 'QRIS API'],
                'full_description' => 'Dewata Fintech memberdayakan pengusaha lokal Bali dengan sistem kasir pintar, transaksi QRIS instan, dan integrasi pembukuan digital otomatis untuk memajukan perekonomian daerah.',
            ],
            [
                'id' => 4,
                'name' => 'Ubud Dev Studio',
                'category' => 'Software Development',
                'category_slug' => 'software-development',
                'location' => 'Gianyar',
                'badge_class' => 'software',
                'description' => 'Spesialis pengembangan aplikasi mobile dan sistem terdistribusi.',
                'logo_bg' => '#eff6ff',
                'logo_color' => '#2563eb',
                'icon_type' => 'cpu',
                'employees' => '15-30 Karyawan',
                'website' => 'https://ubuddevstudio.com',
                'email' => 'dev@ubuddevstudio.com',
                'founded' => '2019',
                'rating' => '4.9',
                'projects_completed' => '95+ Apps',
                'verified' => true,
                'logo_image' => 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=300&h=300&fit=crop',
                'cover_image' => 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1000&h=400&fit=crop',
                'specialties' => ['Cross-Platform Mobile Apps', 'Native iOS & Android', 'GraphQL API Services'],
                'tech_stack' => ['React Native', 'Kotlin', 'Swift', 'GraphQL', 'Firebase'],
                'full_description' => 'Ubud Dev Studio menghadirkan aplikasi iOS dan Android performa tinggi dengan filosofi pengembangan bersih dan teruji (Clean Code & TDD). Berbasis di pusat kebudayaan Ubud.',
            ],
            [
                'id' => 5,
                'name' => 'Canggu Digital',
                'category' => 'Creative Agency',
                'category_slug' => 'creative-agency',
                'location' => 'Badung',
                'badge_class' => 'creative',
                'description' => 'Menciptakan pengalaman digital yang imersif dan branding visual.',
                'logo_bg' => '#f0fdf4',
                'logo_color' => '#16a34a',
                'icon_type' => 'magic',
                'employees' => '10-25 Karyawan',
                'website' => 'https://canggudigital.com',
                'email' => 'create@canggudigital.com',
                'founded' => '2021',
                'rating' => '4.9',
                'projects_completed' => '60+ WebGL Sites',
                'verified' => true,
                'logo_image' => 'https://images.unsplash.com/photo-1542744094-3a3172720189?w=300&h=300&fit=crop',
                'cover_image' => 'https://images.unsplash.com/photo-1600508774634-4e11d34730e2?w=1000&h=400&fit=crop',
                'specialties' => ['3D WebGL Experiences', 'Motion & Visual Branding', 'Tourism Tech Solutions'],
                'tech_stack' => ['Three.js', 'Next.js', 'GSAP', 'Blender', 'TailwindCSS'],
                'full_description' => 'Canggu Digital mengombinasikan desain 3D WebGL, animasi dinamis, dan riset UX mendalam untuk bisnis pariwisata, gaya hidup, dan teknologi internasional di kawasan Canggu.',
            ],
            [
                'id' => 6,
                'name' => 'Sanur Tech',
                'category' => 'Startup',
                'category_slug' => 'startup',
                'location' => 'Denpasar',
                'badge_class' => 'startup',
                'description' => 'Platform logistik pintar yang menghubungkan pengusaha lokal.',
                'logo_bg' => '#fff1f2',
                'logo_color' => '#e11d48',
                'icon_type' => 'cloud',
                'employees' => '20-40 Karyawan',
                'website' => 'https://sanurtech.id',
                'email' => 'info@sanurtech.id',
                'founded' => '2022',
                'rating' => '4.8',
                'projects_completed' => '150k+ Pengiriman',
                'verified' => true,
                'logo_image' => 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=300&h=300&fit=crop',
                'cover_image' => 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=1000&h=400&fit=crop',
                'specialties' => ['AI Smart Logistics Routing', 'Supply Chain Management', 'Real-time Tracking API'],
                'tech_stack' => ['Python', 'Django', 'FastAPI', 'Flutter', 'Redis'],
                'full_description' => 'Sanur Tech mengembangkan platform manajemen rantai pasok berbasis kecerdasan buatan untuk merasionalkan rute pengiriman dan logistik barang antar pulau di Indonesia.',
            ],
            [
                'id' => 7,
                'name' => 'Nusa Media Labs',
                'category' => 'Software Development',
                'category_slug' => 'software-development',
                'location' => 'Badung',
                'badge_class' => 'software',
                'description' => 'Riset dan pengembang analitik data skala besar & AI.',
                'logo_bg' => '#eff6ff',
                'logo_color' => '#2563eb',
                'icon_type' => 'sparkles',
                'employees' => '30-60 Karyawan',
                'website' => 'https://nusamedia.io',
                'email' => 'labs@nusamedia.io',
                'founded' => '2017',
                'rating' => '5.0',
                'projects_completed' => '110+ Data Pipelines',
                'verified' => true,
                'logo_image' => 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=300&h=300&fit=crop',
                'cover_image' => 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1000&h=400&fit=crop',
                'specialties' => ['Predictive AI Analytics', 'Big Data Engineering', 'Machine Learning Models'],
                'tech_stack' => ['Python', 'TensorFlow', 'PyTorch', 'Apache Spark', 'AWS'],
                'full_description' => 'Nusa Media Labs adalah perusahaan analitik data dan pembelajaran mesin yang membantu perusahaan mengambil keputusan strategis berpatokan pada data riil.',
            ],
            [
                'id' => 8,
                'name' => 'Kuta Cloud Systems',
                'category' => 'Software Development',
                'category_slug' => 'software-development',
                'location' => 'Badung',
                'badge_class' => 'software',
                'description' => 'Penyedia infrastruktur cloud dan keamanan siber terpercaya.',
                'logo_bg' => '#eff6ff',
                'logo_color' => '#2563eb',
                'icon_type' => 'terminal',
                'employees' => '40-80 Karyawan',
                'website' => 'https://kutacloud.co.id',
                'email' => 'security@kutacloud.co.id',
                'founded' => '2016',
                'rating' => '4.8',
                'projects_completed' => '75+ Cloud Migrations',
                'verified' => true,
                'logo_image' => 'https://images.unsplash.com/photo-1573164713988-8665fc963095?w=300&h=300&fit=crop',
                'cover_image' => 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1000&h=400&fit=crop',
                'specialties' => ['Multi-Cloud Migration', 'DevOps & CI/CD Pipelines', 'Cybersecurity Auditing'],
                'tech_stack' => ['Terraform', 'Kubernetes', 'AWS', 'GCP', 'Ansible'],
                'full_description' => 'Kuta Cloud Systems berfokus pada migrasi arsitektur cloud, DevOps CI/CD pipeline, serta perlindungan infrastruktur server dari serangan siber.',
            ],
            [
                'id' => 9,
                'name' => 'Seminyak Creative Tech',
                'category' => 'Creative Agency',
                'category_slug' => 'creative-agency',
                'location' => 'Badung',
                'badge_class' => 'creative',
                'description' => 'Studio kreatif produk digital berfokus pada merek kemewahan.',
                'logo_bg' => '#f0fdf4',
                'logo_color' => '#16a34a',
                'icon_type' => 'layers',
                'employees' => '15-25 Karyawan',
                'website' => 'https://seminyakcreative.com',
                'email' => 'hi@seminyakcreative.com',
                'founded' => '2020',
                'rating' => '4.9',
                'projects_completed' => '65+ Brand Systems',
                'verified' => true,
                'logo_image' => 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=300&h=300&fit=crop',
                'cover_image' => 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=1000&h=400&fit=crop',
                'specialties' => ['Luxury Digital Branding', 'Motion Graphics Animation', 'Design System Architecture'],
                'tech_stack' => ['Figma', 'After Effects', 'React', 'CSS Modules'],
                'full_description' => 'Seminyak Creative Tech menggabungkan estetika seni lokal Bali dengan teknologi front-end presisi tinggi untuk menghadirkan situs web berkelas dunia.',
            ],
            [
                'id' => 10,
                'name' => 'Dewata AI Labs',
                'category' => 'Startup',
                'category_slug' => 'startup',
                'location' => 'Denpasar',
                'badge_class' => 'startup',
                'description' => 'Solusi agen AI & otomatisasi untuk sektor hospitality.',
                'logo_bg' => '#fff1f2',
                'logo_color' => '#e11d48',
                'icon_type' => 'sparkles',
                'employees' => '10-20 Karyawan',
                'website' => 'https://dewata.ai',
                'email' => 'hello@dewata.ai',
                'founded' => '2023',
                'rating' => '5.0',
                'projects_completed' => '30+ AI Agents',
                'verified' => true,
                'logo_image' => 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=300&h=300&fit=crop',
                'cover_image' => 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1000&h=400&fit=crop',
                'specialties' => ['Conversational AI Chatbots', 'LLM Integration & RAG', 'Hospitality Automation'],
                'tech_stack' => ['Python', 'OpenAI API', 'LangChain', 'FastAPI', 'React'],
                'full_description' => 'Dewata AI Labs membangun solusi conversational AI yang membantu sektor perhotelan dan pariwisata menangani pertanyaan tamu 24/7 secara otomatis.',
            ],
            [
                'id' => 11,
                'name' => 'Jimbaran Cyber',
                'category' => 'Software Development',
                'category_slug' => 'software-development',
                'location' => 'Badung',
                'badge_class' => 'software',
                'description' => 'Pengembang aplikasi perbankan dan kesehatan skala enterprise.',
                'logo_bg' => '#eff6ff',
                'logo_color' => '#2563eb',
                'icon_type' => 'building',
                'employees' => '50-100 Karyawan',
                'website' => 'https://jimbarancyber.com',
                'email' => 'info@jimbarancyber.com',
                'founded' => '2015',
                'rating' => '4.9',
                'projects_completed' => '140+ Core Systems',
                'verified' => true,
                'logo_image' => 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=300&h=300&fit=crop',
                'cover_image' => 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=1000&h=400&fit=crop',
                'specialties' => ['Banking Core Systems', 'Hospital Information Systems', 'Government IT Solutions'],
                'tech_stack' => ['Java', 'Spring Boot', 'Angular', 'Oracle', 'Docker'],
                'full_description' => 'Jimbaran Cyber menyediakan solusi perbankan, sistem informasi rumah sakit, dan aplikasi pemerintahan dengan standar keamanan tinggi.',
            ],
            [
                'id' => 12,
                'name' => 'Benoa Web Studio',
                'category' => 'Creative Agency',
                'category_slug' => 'creative-agency',
                'location' => 'Badung',
                'badge_class' => 'creative',
                'description' => 'Optimasi e-commerce dan strategi pemasaran digital berorientasi hasil.',
                'logo_bg' => '#f0fdf4',
                'logo_color' => '#16a34a',
                'icon_type' => 'camera',
                'employees' => '15-30 Karyawan',
                'website' => 'https://benoaweb.com',
                'email' => 'growth@benoaweb.com',
                'founded' => '2019',
                'rating' => '4.7',
                'projects_completed' => '90+ E-Commerce Sites',
                'verified' => true,
                'logo_image' => 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=300&h=300&fit=crop',
                'cover_image' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1000&h=400&fit=crop',
                'specialties' => ['Global Export E-Commerce', 'Performance Marketing', 'SEO Optimization'],
                'tech_stack' => ['Shopify', 'Laravel', 'SEO Tools', 'Meta Ads', 'Google Ads'],
                'full_description' => 'Benoa Web Studio membantu merek lokal memperluas jangkuan pasar ekspor melalui optimasi mesin pencari, toko online, dan pemasaran digital berbasis performa.',
            ],
            [
                'id' => 13,
                'name' => 'Tabanan Code House',
                'category' => 'Software Development',
                'category_slug' => 'software-development',
                'location' => 'Tabanan',
                'badge_class' => 'software',
                'description' => 'Integrasi sistem agritech & pemantauan IoT untuk pertanian.',
                'logo_bg' => '#eff6ff',
                'logo_color' => '#2563eb',
                'icon_type' => 'cpu',
                'employees' => '10-20 Karyawan',
                'website' => 'https://tabanancode.id',
                'email' => 'agri@tabanancode.id',
                'founded' => '2021',
                'rating' => '4.9',
                'projects_completed' => '50+ Smart Farms',
                'verified' => true,
                'logo_image' => 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=300&h=300&fit=crop',
                'cover_image' => 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=1000&h=400&fit=crop',
                'specialties' => ['IoT Sensors Hardware', 'Micro-climate Analytics', 'Organic Agritech Software'],
                'tech_stack' => ['C++', 'Python', 'MQTT', 'Raspberry Pi', 'Vue.js'],
                'full_description' => 'Tabanan Code House berfokus pada integrasi peranti keras sensor IoT dan aplikasi pemantauan iklim mikro untuk mendukung sektor pertanian organik Bali.',
            ],
            [
                'id' => 14,
                'name' => 'Singaraja Tech',
                'category' => 'Startup',
                'category_slug' => 'startup',
                'location' => 'Buleleng',
                'badge_class' => 'startup',
                'description' => 'Pusat inkubasi talenta digital dan edutech Bali Utara.',
                'logo_bg' => '#fff1f2',
                'logo_color' => '#e11d48',
                'icon_type' => 'terminal',
                'employees' => '10-25 Karyawan',
                'website' => 'https://singarajatech.id',
                'email' => 'academy@singarajatech.id',
                'founded' => '2022',
                'rating' => '4.8',
                'projects_completed' => '1.2k+ Graduates',
                'verified' => true,
                'logo_image' => 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=300&h=300&fit=crop',
                'cover_image' => 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=1000&h=400&fit=crop',
                'specialties' => ['Fullstack Coding Bootcamp', 'Developer Talent Placement', 'Edutech Platform'],
                'tech_stack' => ['Laravel', 'AlpineJS', 'TailwindCSS', 'MySQL'],
                'full_description' => 'Singaraja Tech memberdayakan pemuda dan mahasiswa Bali Utara dengan kurikulum coding intensif, bootcamp, dan penyaluran kerja ke industri digital.',
            ],
            [
                'id' => 15,
                'name' => 'Uluwatu Digital Innovation',
                'category' => 'Creative Agency',
                'category_slug' => 'creative-agency',
                'location' => 'Badung',
                'badge_class' => 'creative',
                'description' => 'Sinematografi digital, branding luxury, dan web interaktif.',
                'logo_bg' => '#f0fdf4',
                'logo_color' => '#16a34a',
                'icon_type' => 'magic',
                'employees' => '15-30 Karyawan',
                'website' => 'https://uluwatudigital.com',
                'email' => 'hello@uluwatudigital.com',
                'founded' => '2020',
                'rating' => '4.9',
                'projects_completed' => '45+ Luxury Campaigns',
                'verified' => true,
                'logo_image' => 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=300&h=300&fit=crop',
                'cover_image' => 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1000&h=400&fit=crop',
                'specialties' => ['Luxury Brand Storytelling', 'Cinematic Video Production', 'High-end Resort Web Design'],
                'tech_stack' => ['Premiere Pro', 'Figma', 'Webflow', 'Node.js'],
                'full_description' => 'Uluwatu Digital Innovation menghadirkan narasi visual yang kuat, sinematografi brand, dan situs web interaktif untuk resort mewah dan destinasi eksklusif.',
            ]
        ];

        return view('industry.industry', compact('companies'));
    }
}
